DROP SCHEMA IF EXISTS FINANCEIRO CASCADE;
CREATE SCHEMA FINANCEIRO;
SET SCHEMA FINANCEIRO;

CREATE TABLE tipo_orcamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    CONSTRAINT uk_tipo_orcamento_nome UNIQUE (nome)
);

CREATE TABLE item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    unidade VARCHAR(50),
    CONSTRAINT uk_item_nome UNIQUE (nome)
);

CREATE TABLE orcamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nup VARCHAR(17) NOT NULL,
    tipo_orcamento_id BIGINT NOT NULL,
    data_criacao TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    valor_total DECIMAL(12, 2) NOT NULL,
    CONSTRAINT uk_orcamento_nup UNIQUE (nup),
    CONSTRAINT ck_orcamento_status CHECK (status IN ('ABERTO', 'FINALIZADO')),
    CONSTRAINT fk_orcamento_tipo FOREIGN KEY (tipo_orcamento_id) REFERENCES tipo_orcamento(id)
);

CREATE TABLE item_orcamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    quantidade DECIMAL(12, 2) NOT NULL,
    valor_unitario DECIMAL(12, 2) NOT NULL,
    valor_total DECIMAL(12, 2) NOT NULL,
    quantidade_acumulada DECIMAL(12, 2) NOT NULL DEFAULT 0,
    orcamento_id BIGINT NOT NULL,
    CONSTRAINT fk_item_orcamento_item FOREIGN KEY (item_id) REFERENCES item(id),
    CONSTRAINT fk_item_orcamento_orcamento FOREIGN KEY (orcamento_id) REFERENCES orcamento(id)
);

CREATE TABLE medicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(50) NOT NULL,
    data_medicao DATE NOT NULL,
    valor_medicao DECIMAL(12, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    observacao VARCHAR(500),
    orcamento_id BIGINT NOT NULL,
    CONSTRAINT uk_medicao_numero UNIQUE (numero),
    CONSTRAINT ck_medicao_status CHECK (status IN ('ABERTA', 'VALIDADA')),
    CONSTRAINT fk_medicao_orcamento FOREIGN KEY (orcamento_id) REFERENCES orcamento(id)
);

CREATE TABLE item_medicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantidade_medida DECIMAL(12, 2) NOT NULL,
    valor_total_medido DECIMAL(12, 2) NOT NULL,
    item_orcamento_id BIGINT NOT NULL,
    medicao_id BIGINT NOT NULL,
    CONSTRAINT fk_item_medicao_item_orcamento FOREIGN KEY (item_orcamento_id) REFERENCES item_orcamento(id),
    CONSTRAINT fk_item_medicao_medicao FOREIGN KEY (medicao_id) REFERENCES medicao(id)
);
